export {
  ResendProvider,
  type ResendConfig,
  type SendEmailOptions,
  type SendEmailResult,
  type BatchMessage,
  type BatchSendResult,
  appointmentConfirmationHtml,
  appointmentReminderHtml,
  reviewRequestHtml,
  invoiceSentHtml,
  welcomeHtml,
  passwordResetHtml,
  emailVerificationHtml,
} from "./providers/resend.js";
