import { z } from "zod";
export declare const verticalSchema: z.ZodEnum<["rubbish_removals", "moving_company", "plumbing", "hvac", "electrical", "roofing", "landscaping", "pest_control", "cleaning", "general_contractor"]>;
export declare const contactSourceSchema: z.ZodEnum<["manual", "phone", "sms", "email", "webform", "referral", "google_ads", "facebook_ads", "yelp", "import"]>;
export declare const dealStageSchema: z.ZodEnum<["new_lead", "contacted", "qualified", "quote_sent", "negotiation", "won", "lost"]>;
export declare const activityTypeSchema: z.ZodEnum<["call", "sms", "email", "note", "meeting", "task", "deal_stage_change", "ai_interaction", "form_submission", "appointment_booked", "appointment_completed", "payment_received"]>;
export declare const channelTypeSchema: z.ZodEnum<["sms", "email", "call", "whatsapp", "webchat"]>;
export declare const conversationStatusSchema: z.ZodEnum<["open", "closed", "snoozed"]>;
export declare const messageDirectionSchema: z.ZodEnum<["inbound", "outbound"]>;
export declare const messageSenderTypeSchema: z.ZodEnum<["contact", "user", "ai"]>;
export declare const messageStatusSchema: z.ZodEnum<["sent", "delivered", "read", "failed"]>;
export declare const aiAgentTypeSchema: z.ZodEnum<["phone", "sms", "chat", "review"]>;
export declare const callDirectionSchema: z.ZodEnum<["inbound", "outbound"]>;
export declare const callOutcomeSchema: z.ZodEnum<["booked", "qualified", "escalated", "spam", "voicemail"]>;
export declare const appointmentStatusSchema: z.ZodEnum<["scheduled", "confirmed", "in_progress", "completed", "cancelled", "no_show"]>;
export declare const dayOfWeekSchema: z.ZodEnum<["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"]>;
export declare const orgMemberRoleSchema: z.ZodEnum<["owner", "admin", "manager", "member"]>;
export declare const organizationSchema: z.ZodObject<{
    id: z.ZodString;
    name: z.ZodString;
    slug: z.ZodString;
    vertical: z.ZodEnum<["rubbish_removals", "moving_company", "plumbing", "hvac", "electrical", "roofing", "landscaping", "pest_control", "cleaning", "general_contractor"]>;
    timezone: z.ZodString;
    phone: z.ZodNullable<z.ZodString>;
    email: z.ZodNullable<z.ZodString>;
    website: z.ZodNullable<z.ZodString>;
    address: z.ZodNullable<z.ZodString>;
    logoUrl: z.ZodNullable<z.ZodString>;
    settings: z.ZodRecord<z.ZodString, z.ZodUnknown>;
    createdAt: z.ZodDate;
    updatedAt: z.ZodDate;
}, "strip", z.ZodTypeAny, {
    name: string;
    phone: string | null;
    email: string | null;
    id: string;
    createdAt: Date;
    updatedAt: Date;
    vertical: "hvac" | "plumbing" | "rubbish_removals" | "moving_company" | "electrical" | "roofing" | "landscaping" | "pest_control" | "cleaning" | "general_contractor";
    slug: string;
    timezone: string;
    website: string | null;
    address: string | null;
    logoUrl: string | null;
    settings: Record<string, unknown>;
}, {
    name: string;
    phone: string | null;
    email: string | null;
    id: string;
    createdAt: Date;
    updatedAt: Date;
    vertical: "hvac" | "plumbing" | "rubbish_removals" | "moving_company" | "electrical" | "roofing" | "landscaping" | "pest_control" | "cleaning" | "general_contractor";
    slug: string;
    timezone: string;
    website: string | null;
    address: string | null;
    logoUrl: string | null;
    settings: Record<string, unknown>;
}>;
export declare const contactSchema: z.ZodObject<{
    id: z.ZodString;
    orgId: z.ZodString;
    firstName: z.ZodString;
    lastName: z.ZodString;
    email: z.ZodNullable<z.ZodString>;
    phone: z.ZodNullable<z.ZodString>;
    companyId: z.ZodNullable<z.ZodString>;
    source: z.ZodEnum<["manual", "phone", "sms", "email", "webform", "referral", "google_ads", "facebook_ads", "yelp", "import"]>;
    aiScore: z.ZodNumber;
    tags: z.ZodArray<z.ZodString, "many">;
    customFields: z.ZodRecord<z.ZodString, z.ZodUnknown>;
    createdAt: z.ZodDate;
    updatedAt: z.ZodDate;
}, "strip", z.ZodTypeAny, {
    phone: string | null;
    source: "phone" | "webform" | "referral" | "google_ads" | "sms" | "yelp" | "email" | "manual" | "facebook_ads" | "import";
    email: string | null;
    id: string;
    orgId: string;
    createdAt: Date;
    updatedAt: Date;
    firstName: string;
    lastName: string;
    companyId: string | null;
    aiScore: number;
    tags: string[];
    customFields: Record<string, unknown>;
}, {
    phone: string | null;
    source: "phone" | "webform" | "referral" | "google_ads" | "sms" | "yelp" | "email" | "manual" | "facebook_ads" | "import";
    email: string | null;
    id: string;
    orgId: string;
    createdAt: Date;
    updatedAt: Date;
    firstName: string;
    lastName: string;
    companyId: string | null;
    aiScore: number;
    tags: string[];
    customFields: Record<string, unknown>;
}>;
export declare const companySchema: z.ZodObject<{
    id: z.ZodString;
    orgId: z.ZodString;
    name: z.ZodString;
    phone: z.ZodNullable<z.ZodString>;
    email: z.ZodNullable<z.ZodString>;
    website: z.ZodNullable<z.ZodString>;
    address: z.ZodNullable<z.ZodString>;
    createdAt: z.ZodDate;
    updatedAt: z.ZodDate;
}, "strip", z.ZodTypeAny, {
    name: string;
    phone: string | null;
    email: string | null;
    id: string;
    orgId: string;
    createdAt: Date;
    updatedAt: Date;
    website: string | null;
    address: string | null;
}, {
    name: string;
    phone: string | null;
    email: string | null;
    id: string;
    orgId: string;
    createdAt: Date;
    updatedAt: Date;
    website: string | null;
    address: string | null;
}>;
export declare const pipelineSchema: z.ZodObject<{
    id: z.ZodString;
    orgId: z.ZodString;
    name: z.ZodString;
    isDefault: z.ZodBoolean;
    createdAt: z.ZodDate;
    updatedAt: z.ZodDate;
}, "strip", z.ZodTypeAny, {
    name: string;
    id: string;
    orgId: string;
    createdAt: Date;
    updatedAt: Date;
    isDefault: boolean;
}, {
    name: string;
    id: string;
    orgId: string;
    createdAt: Date;
    updatedAt: Date;
    isDefault: boolean;
}>;
export declare const pipelineStageSchema: z.ZodObject<{
    id: z.ZodString;
    pipelineId: z.ZodString;
    orgId: z.ZodString;
    name: z.ZodString;
    slug: z.ZodEnum<["new_lead", "contacted", "qualified", "quote_sent", "negotiation", "won", "lost"]>;
    position: z.ZodNumber;
    color: z.ZodString;
    createdAt: z.ZodDate;
    updatedAt: z.ZodDate;
}, "strip", z.ZodTypeAny, {
    name: string;
    id: string;
    orgId: string;
    createdAt: Date;
    updatedAt: Date;
    slug: "new_lead" | "contacted" | "qualified" | "quote_sent" | "negotiation" | "won" | "lost";
    pipelineId: string;
    position: number;
    color: string;
}, {
    name: string;
    id: string;
    orgId: string;
    createdAt: Date;
    updatedAt: Date;
    slug: "new_lead" | "contacted" | "qualified" | "quote_sent" | "negotiation" | "won" | "lost";
    pipelineId: string;
    position: number;
    color: string;
}>;
export declare const dealSchema: z.ZodObject<{
    id: z.ZodString;
    orgId: z.ZodString;
    pipelineId: z.ZodString;
    stageId: z.ZodString;
    contactId: z.ZodString;
    title: z.ZodString;
    value: z.ZodNumber;
    currency: z.ZodString;
    expectedCloseDate: z.ZodNullable<z.ZodDate>;
    assignedTo: z.ZodNullable<z.ZodString>;
    metadata: z.ZodRecord<z.ZodString, z.ZodUnknown>;
    closedAt: z.ZodNullable<z.ZodDate>;
    createdAt: z.ZodDate;
    updatedAt: z.ZodDate;
}, "strip", z.ZodTypeAny, {
    value: number;
    id: string;
    orgId: string;
    contactId: string;
    createdAt: Date;
    updatedAt: Date;
    pipelineId: string;
    stageId: string;
    title: string;
    currency: string;
    expectedCloseDate: Date | null;
    assignedTo: string | null;
    metadata: Record<string, unknown>;
    closedAt: Date | null;
}, {
    value: number;
    id: string;
    orgId: string;
    contactId: string;
    createdAt: Date;
    updatedAt: Date;
    pipelineId: string;
    stageId: string;
    title: string;
    currency: string;
    expectedCloseDate: Date | null;
    assignedTo: string | null;
    metadata: Record<string, unknown>;
    closedAt: Date | null;
}>;
export declare const activitySchema: z.ZodObject<{
    id: z.ZodString;
    orgId: z.ZodString;
    contactId: z.ZodNullable<z.ZodString>;
    dealId: z.ZodNullable<z.ZodString>;
    type: z.ZodEnum<["call", "sms", "email", "note", "meeting", "task", "deal_stage_change", "ai_interaction", "form_submission", "appointment_booked", "appointment_completed", "payment_received"]>;
    title: z.ZodString;
    description: z.ZodNullable<z.ZodString>;
    performedBy: z.ZodNullable<z.ZodString>;
    metadata: z.ZodRecord<z.ZodString, z.ZodUnknown>;
    createdAt: z.ZodDate;
}, "strip", z.ZodTypeAny, {
    type: "sms" | "email" | "call" | "appointment_completed" | "note" | "meeting" | "task" | "deal_stage_change" | "ai_interaction" | "form_submission" | "appointment_booked" | "payment_received";
    id: string;
    orgId: string;
    contactId: string | null;
    createdAt: Date;
    title: string;
    metadata: Record<string, unknown>;
    dealId: string | null;
    description: string | null;
    performedBy: string | null;
}, {
    type: "sms" | "email" | "call" | "appointment_completed" | "note" | "meeting" | "task" | "deal_stage_change" | "ai_interaction" | "form_submission" | "appointment_booked" | "payment_received";
    id: string;
    orgId: string;
    contactId: string | null;
    createdAt: Date;
    title: string;
    metadata: Record<string, unknown>;
    dealId: string | null;
    description: string | null;
    performedBy: string | null;
}>;
export declare const conversationSchema: z.ZodObject<{
    id: z.ZodString;
    orgId: z.ZodString;
    contactId: z.ZodString;
    channel: z.ZodEnum<["sms", "email", "call", "whatsapp", "webchat"]>;
    status: z.ZodEnum<["open", "closed", "snoozed"]>;
    assignedTo: z.ZodNullable<z.ZodString>;
    aiHandled: z.ZodBoolean;
    lastMessageAt: z.ZodNullable<z.ZodDate>;
    unreadCount: z.ZodNumber;
    createdAt: z.ZodDate;
}, "strip", z.ZodTypeAny, {
    status: "open" | "closed" | "snoozed";
    channel: "sms" | "email" | "call" | "whatsapp" | "webchat";
    id: string;
    orgId: string;
    contactId: string;
    lastMessageAt: Date | null;
    unreadCount: number;
    aiHandled: boolean;
    createdAt: Date;
    assignedTo: string | null;
}, {
    status: "open" | "closed" | "snoozed";
    channel: "sms" | "email" | "call" | "whatsapp" | "webchat";
    id: string;
    orgId: string;
    contactId: string;
    lastMessageAt: Date | null;
    unreadCount: number;
    aiHandled: boolean;
    createdAt: Date;
    assignedTo: string | null;
}>;
export declare const messageSchema: z.ZodObject<{
    id: z.ZodString;
    conversationId: z.ZodString;
    orgId: z.ZodString;
    direction: z.ZodEnum<["inbound", "outbound"]>;
    channel: z.ZodEnum<["sms", "email", "call", "whatsapp", "webchat"]>;
    senderType: z.ZodEnum<["contact", "user", "ai"]>;
    senderId: z.ZodNullable<z.ZodString>;
    body: z.ZodString;
    mediaUrls: z.ZodArray<z.ZodString, "many">;
    metadata: z.ZodRecord<z.ZodString, z.ZodUnknown>;
    status: z.ZodEnum<["sent", "delivered", "read", "failed"]>;
    createdAt: z.ZodDate;
}, "strip", z.ZodTypeAny, {
    status: "delivered" | "sent" | "read" | "failed";
    channel: "sms" | "email" | "call" | "whatsapp" | "webchat";
    id: string;
    orgId: string;
    createdAt: Date;
    metadata: Record<string, unknown>;
    conversationId: string;
    direction: "inbound" | "outbound";
    senderType: "contact" | "user" | "ai";
    senderId: string | null;
    body: string;
    mediaUrls: string[];
}, {
    status: "delivered" | "sent" | "read" | "failed";
    channel: "sms" | "email" | "call" | "whatsapp" | "webchat";
    id: string;
    orgId: string;
    createdAt: Date;
    metadata: Record<string, unknown>;
    conversationId: string;
    direction: "inbound" | "outbound";
    senderType: "contact" | "user" | "ai";
    senderId: string | null;
    body: string;
    mediaUrls: string[];
}>;
export declare const appointmentSchema: z.ZodObject<{
    id: z.ZodString;
    orgId: z.ZodString;
    contactId: z.ZodString;
    assignedTo: z.ZodNullable<z.ZodString>;
    title: z.ZodString;
    description: z.ZodNullable<z.ZodString>;
    startTime: z.ZodDate;
    endTime: z.ZodDate;
    status: z.ZodEnum<["scheduled", "confirmed", "in_progress", "completed", "cancelled", "no_show"]>;
    location: z.ZodNullable<z.ZodString>;
    notes: z.ZodNullable<z.ZodString>;
    reminderSentAt: z.ZodNullable<z.ZodDate>;
    googleEventId: z.ZodNullable<z.ZodString>;
    createdAt: z.ZodDate;
    updatedAt: z.ZodDate;
}, "strip", z.ZodTypeAny, {
    status: "scheduled" | "confirmed" | "completed" | "in_progress" | "cancelled" | "no_show";
    id: string;
    orgId: string;
    contactId: string;
    createdAt: Date;
    updatedAt: Date;
    title: string;
    assignedTo: string | null;
    description: string | null;
    startTime: Date;
    endTime: Date;
    location: string | null;
    notes: string | null;
    reminderSentAt: Date | null;
    googleEventId: string | null;
}, {
    status: "scheduled" | "confirmed" | "completed" | "in_progress" | "cancelled" | "no_show";
    id: string;
    orgId: string;
    contactId: string;
    createdAt: Date;
    updatedAt: Date;
    title: string;
    assignedTo: string | null;
    description: string | null;
    startTime: Date;
    endTime: Date;
    location: string | null;
    notes: string | null;
    reminderSentAt: Date | null;
    googleEventId: string | null;
}>;
export declare const availabilityRuleSchema: z.ZodObject<{
    id: z.ZodString;
    orgId: z.ZodString;
    userId: z.ZodString;
    dayOfWeek: z.ZodEnum<["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"]>;
    startTime: z.ZodString;
    endTime: z.ZodString;
    isActive: z.ZodBoolean;
    createdAt: z.ZodDate;
    updatedAt: z.ZodDate;
}, "strip", z.ZodTypeAny, {
    id: string;
    orgId: string;
    isActive: boolean;
    createdAt: Date;
    updatedAt: Date;
    userId: string;
    startTime: string;
    endTime: string;
    dayOfWeek: "monday" | "tuesday" | "wednesday" | "thursday" | "friday" | "saturday" | "sunday";
}, {
    id: string;
    orgId: string;
    isActive: boolean;
    createdAt: Date;
    updatedAt: Date;
    userId: string;
    startTime: string;
    endTime: string;
    dayOfWeek: "monday" | "tuesday" | "wednesday" | "thursday" | "friday" | "saturday" | "sunday";
}>;
export declare const aiAgentSchema: z.ZodObject<{
    id: z.ZodString;
    orgId: z.ZodString;
    type: z.ZodEnum<["phone", "sms", "chat", "review"]>;
    name: z.ZodString;
    systemPrompt: z.ZodString;
    vertical: z.ZodEnum<["rubbish_removals", "moving_company", "plumbing", "hvac", "electrical", "roofing", "landscaping", "pest_control", "cleaning", "general_contractor"]>;
    settings: z.ZodRecord<z.ZodString, z.ZodUnknown>;
    isActive: z.ZodBoolean;
    createdAt: z.ZodDate;
    updatedAt: z.ZodDate;
}, "strip", z.ZodTypeAny, {
    type: "phone" | "sms" | "chat" | "review";
    name: string;
    id: string;
    orgId: string;
    isActive: boolean;
    createdAt: Date;
    updatedAt: Date;
    vertical: "hvac" | "plumbing" | "rubbish_removals" | "moving_company" | "electrical" | "roofing" | "landscaping" | "pest_control" | "cleaning" | "general_contractor";
    settings: Record<string, unknown>;
    systemPrompt: string;
}, {
    type: "phone" | "sms" | "chat" | "review";
    name: string;
    id: string;
    orgId: string;
    isActive: boolean;
    createdAt: Date;
    updatedAt: Date;
    vertical: "hvac" | "plumbing" | "rubbish_removals" | "moving_company" | "electrical" | "roofing" | "landscaping" | "pest_control" | "cleaning" | "general_contractor";
    settings: Record<string, unknown>;
    systemPrompt: string;
}>;
export declare const aiCallLogSchema: z.ZodObject<{
    id: z.ZodString;
    orgId: z.ZodString;
    agentId: z.ZodString;
    contactId: z.ZodNullable<z.ZodString>;
    conversationId: z.ZodNullable<z.ZodString>;
    twilioCallSid: z.ZodNullable<z.ZodString>;
    direction: z.ZodEnum<["inbound", "outbound"]>;
    durationSeconds: z.ZodNumber;
    recordingUrl: z.ZodNullable<z.ZodString>;
    transcript: z.ZodNullable<z.ZodString>;
    summary: z.ZodNullable<z.ZodString>;
    sentiment: z.ZodNullable<z.ZodString>;
    outcome: z.ZodEnum<["booked", "qualified", "escalated", "spam", "voicemail"]>;
    createdAt: z.ZodDate;
}, "strip", z.ZodTypeAny, {
    id: string;
    orgId: string;
    contactId: string | null;
    createdAt: Date;
    conversationId: string | null;
    direction: "inbound" | "outbound";
    agentId: string;
    twilioCallSid: string | null;
    durationSeconds: number;
    recordingUrl: string | null;
    transcript: string | null;
    summary: string | null;
    sentiment: string | null;
    outcome: "qualified" | "booked" | "escalated" | "spam" | "voicemail";
}, {
    id: string;
    orgId: string;
    contactId: string | null;
    createdAt: Date;
    conversationId: string | null;
    direction: "inbound" | "outbound";
    agentId: string;
    twilioCallSid: string | null;
    durationSeconds: number;
    recordingUrl: string | null;
    transcript: string | null;
    summary: string | null;
    sentiment: string | null;
    outcome: "qualified" | "booked" | "escalated" | "spam" | "voicemail";
}>;
export declare const createContactInput: z.ZodObject<{
    firstName: z.ZodString;
    lastName: z.ZodString;
    email: z.ZodOptional<z.ZodString>;
    phone: z.ZodOptional<z.ZodString>;
    companyId: z.ZodOptional<z.ZodString>;
    source: z.ZodDefault<z.ZodEnum<["manual", "phone", "sms", "email", "webform", "referral", "google_ads", "facebook_ads", "yelp", "import"]>>;
    tags: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    customFields: z.ZodDefault<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
}, "strip", z.ZodTypeAny, {
    source: "phone" | "webform" | "referral" | "google_ads" | "sms" | "yelp" | "email" | "manual" | "facebook_ads" | "import";
    firstName: string;
    lastName: string;
    tags: string[];
    customFields: Record<string, unknown>;
    phone?: string | undefined;
    email?: string | undefined;
    companyId?: string | undefined;
}, {
    firstName: string;
    lastName: string;
    phone?: string | undefined;
    source?: "phone" | "webform" | "referral" | "google_ads" | "sms" | "yelp" | "email" | "manual" | "facebook_ads" | "import" | undefined;
    email?: string | undefined;
    companyId?: string | undefined;
    tags?: string[] | undefined;
    customFields?: Record<string, unknown> | undefined;
}>;
export declare const updateContactInput: z.ZodObject<{
    firstName: z.ZodOptional<z.ZodString>;
    lastName: z.ZodOptional<z.ZodString>;
    email: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    phone: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    companyId: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    source: z.ZodOptional<z.ZodDefault<z.ZodEnum<["manual", "phone", "sms", "email", "webform", "referral", "google_ads", "facebook_ads", "yelp", "import"]>>>;
    tags: z.ZodOptional<z.ZodDefault<z.ZodArray<z.ZodString, "many">>>;
    customFields: z.ZodOptional<z.ZodDefault<z.ZodRecord<z.ZodString, z.ZodUnknown>>>;
}, "strip", z.ZodTypeAny, {
    phone?: string | undefined;
    source?: "phone" | "webform" | "referral" | "google_ads" | "sms" | "yelp" | "email" | "manual" | "facebook_ads" | "import" | undefined;
    email?: string | undefined;
    firstName?: string | undefined;
    lastName?: string | undefined;
    companyId?: string | undefined;
    tags?: string[] | undefined;
    customFields?: Record<string, unknown> | undefined;
}, {
    phone?: string | undefined;
    source?: "phone" | "webform" | "referral" | "google_ads" | "sms" | "yelp" | "email" | "manual" | "facebook_ads" | "import" | undefined;
    email?: string | undefined;
    firstName?: string | undefined;
    lastName?: string | undefined;
    companyId?: string | undefined;
    tags?: string[] | undefined;
    customFields?: Record<string, unknown> | undefined;
}>;
export declare const createDealInput: z.ZodObject<{
    pipelineId: z.ZodString;
    stageId: z.ZodString;
    contactId: z.ZodString;
    title: z.ZodString;
    value: z.ZodDefault<z.ZodNumber>;
    currency: z.ZodDefault<z.ZodString>;
    expectedCloseDate: z.ZodOptional<z.ZodDate>;
    assignedTo: z.ZodOptional<z.ZodString>;
    metadata: z.ZodDefault<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
}, "strip", z.ZodTypeAny, {
    value: number;
    contactId: string;
    pipelineId: string;
    stageId: string;
    title: string;
    currency: string;
    metadata: Record<string, unknown>;
    expectedCloseDate?: Date | undefined;
    assignedTo?: string | undefined;
}, {
    contactId: string;
    pipelineId: string;
    stageId: string;
    title: string;
    value?: number | undefined;
    currency?: string | undefined;
    expectedCloseDate?: Date | undefined;
    assignedTo?: string | undefined;
    metadata?: Record<string, unknown> | undefined;
}>;
export declare const updateDealInput: z.ZodObject<{
    pipelineId: z.ZodOptional<z.ZodString>;
    stageId: z.ZodOptional<z.ZodString>;
    contactId: z.ZodOptional<z.ZodString>;
    title: z.ZodOptional<z.ZodString>;
    value: z.ZodOptional<z.ZodDefault<z.ZodNumber>>;
    currency: z.ZodOptional<z.ZodDefault<z.ZodString>>;
    expectedCloseDate: z.ZodOptional<z.ZodOptional<z.ZodDate>>;
    assignedTo: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    metadata: z.ZodOptional<z.ZodDefault<z.ZodRecord<z.ZodString, z.ZodUnknown>>>;
}, "strip", z.ZodTypeAny, {
    value?: number | undefined;
    contactId?: string | undefined;
    pipelineId?: string | undefined;
    stageId?: string | undefined;
    title?: string | undefined;
    currency?: string | undefined;
    expectedCloseDate?: Date | undefined;
    assignedTo?: string | undefined;
    metadata?: Record<string, unknown> | undefined;
}, {
    value?: number | undefined;
    contactId?: string | undefined;
    pipelineId?: string | undefined;
    stageId?: string | undefined;
    title?: string | undefined;
    currency?: string | undefined;
    expectedCloseDate?: Date | undefined;
    assignedTo?: string | undefined;
    metadata?: Record<string, unknown> | undefined;
}>;
export declare const createAppointmentInput: z.ZodObject<{
    contactId: z.ZodString;
    assignedTo: z.ZodOptional<z.ZodString>;
    title: z.ZodString;
    description: z.ZodOptional<z.ZodString>;
    startTime: z.ZodDate;
    endTime: z.ZodDate;
    location: z.ZodOptional<z.ZodString>;
    notes: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    contactId: string;
    title: string;
    startTime: Date;
    endTime: Date;
    assignedTo?: string | undefined;
    description?: string | undefined;
    location?: string | undefined;
    notes?: string | undefined;
}, {
    contactId: string;
    title: string;
    startTime: Date;
    endTime: Date;
    assignedTo?: string | undefined;
    description?: string | undefined;
    location?: string | undefined;
    notes?: string | undefined;
}>;
export declare const updateAppointmentInput: z.ZodObject<{
    contactId: z.ZodOptional<z.ZodString>;
    assignedTo: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    title: z.ZodOptional<z.ZodString>;
    description: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    startTime: z.ZodOptional<z.ZodDate>;
    endTime: z.ZodOptional<z.ZodDate>;
    location: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    notes: z.ZodOptional<z.ZodOptional<z.ZodString>>;
}, "strip", z.ZodTypeAny, {
    contactId?: string | undefined;
    title?: string | undefined;
    assignedTo?: string | undefined;
    description?: string | undefined;
    startTime?: Date | undefined;
    endTime?: Date | undefined;
    location?: string | undefined;
    notes?: string | undefined;
}, {
    contactId?: string | undefined;
    title?: string | undefined;
    assignedTo?: string | undefined;
    description?: string | undefined;
    startTime?: Date | undefined;
    endTime?: Date | undefined;
    location?: string | undefined;
    notes?: string | undefined;
}>;
export declare const createMessageInput: z.ZodObject<{
    conversationId: z.ZodString;
    direction: z.ZodEnum<["inbound", "outbound"]>;
    channel: z.ZodEnum<["sms", "email", "call", "whatsapp", "webchat"]>;
    senderType: z.ZodEnum<["contact", "user", "ai"]>;
    senderId: z.ZodOptional<z.ZodString>;
    body: z.ZodString;
    mediaUrls: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    metadata: z.ZodDefault<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
}, "strip", z.ZodTypeAny, {
    channel: "sms" | "email" | "call" | "whatsapp" | "webchat";
    metadata: Record<string, unknown>;
    conversationId: string;
    direction: "inbound" | "outbound";
    senderType: "contact" | "user" | "ai";
    body: string;
    mediaUrls: string[];
    senderId?: string | undefined;
}, {
    channel: "sms" | "email" | "call" | "whatsapp" | "webchat";
    conversationId: string;
    direction: "inbound" | "outbound";
    senderType: "contact" | "user" | "ai";
    body: string;
    metadata?: Record<string, unknown> | undefined;
    senderId?: string | undefined;
    mediaUrls?: string[] | undefined;
}>;
export type CreateContactInput = z.infer<typeof createContactInput>;
export type UpdateContactInput = z.infer<typeof updateContactInput>;
export type CreateDealInput = z.infer<typeof createDealInput>;
export type UpdateDealInput = z.infer<typeof updateDealInput>;
export type CreateAppointmentInput = z.infer<typeof createAppointmentInput>;
export type UpdateAppointmentInput = z.infer<typeof updateAppointmentInput>;
export type CreateMessageInput = z.infer<typeof createMessageInput>;
//# sourceMappingURL=index.d.ts.map